### ISSUE TITLE
root filesystem extraction failed: extract command failed

### ISSUE THREAD

**Issue by MeiDongI** [bichangwei/PMAT#1]
Hi, I tried to assemble the mitochondrial genome using hifi data, but I encountered the following problem and don't know how to solve it.

Here's the command I ran:
PMAT all -i m64048_201207_170421.clean.fa -o hifi_assembly -st hifi -g 500M

This is the output:
Reads break start...ed subsets 549.85s <<<<<<
>>> 2023-06-14 16:45:20
[ INFO 2023-06-14 16:54:08 ] The raw sequence number is: 1759210
[ INFO 2023-06-14 16:54:08 ] The processed sequence number is: 1759213
Reads break end. >>> 2023-06-14 16:54:08
The path of Newbler : /w/00/g/g04/user613/pmat_test/PMAT/container/runAssembly.sif
Reads assembly start...
>>> 2023-06-14 16:54:08
INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting /w/00/g/g04/user613/pmat_test/PMAT/container/runAssembly.sif: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /w/00/u/user613/miniconda3/envs/PMAT/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /w/00/u/user613/miniconda3/envs/PMAT/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /w/00/u/user613/miniconda3/envs/PMAT/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs: /w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs: no version information available (required by /w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs)
/w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs: symbol lookup error: /w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs: undefined symbol: lzo1x_1_compress
: exit status 127
Reads assembly end. >>> 2023-06-14 16:54:13
Assembly results path : /w/00/g/g04/user613/pmat_test/hifi_assembly/assembly_result
Traceback (most recent call last):
  File "modules/PMAT.py", line 629, in <module>
    args.func(args)
  File "modules/PMAT.py", line 115, in all
    assembly_output = newbler_assembly.run_newbler(args.cpu, assembly_seq_cut_path, Output, args.minidentity, args.minoverlaplen)
  File "/w/00/g/g04/user613/pmat_test/PMAT/bin/../modules/newbler_assembly.py", line 55, in run_newbler
    for rmopt in [os.path.join(newbler_output, opt) for opt in os.listdir(newbler_output) if opt.startswith('454')]:
FileNotFoundError: [Errno 2] No such file or directory: '/w/00/g/g04/user613/pmat_test/hifi_assembly/assembly_result'
[26793] Failed to execute script 'PMAT' due to unhandled exception!

**Comment by bichangwei** [comment]
Hi，
Thank you for using PMAT.
Can you tell me how you installed PMAT, currently PMAT can only be installed according to the method provided by README.

**Comment by bichangwei** [comment]
Can you show me the command `tree -h . /PMAT` print message.

**Comment by bichangwei** [comment]
Can you show me the command **`tree -h . /PMAT`** print message.

**Comment by Mei0110** [comment]
(base) [user613@scz3]/w/00/g/g04/user613/pmat_test% tree -h ./PMAT
[   6]  ./PMAT
├── [   1]  bin
│   └── [ 12M]  PMAT
├── [   4]  Conserved_PCGs_db
│   ├── [495K]  Plant_conserved_mtgene_nt.fa
│   ├── [ 45K]  Plant_conserved_mtgene_nt.fa.nhr
│   ├── [6.5K]  Plant_conserved_mtgene_nt.fa.nin
│   └── [121K]  Plant_conserved_mtgene_nt.fa.nsq
├── [   1]  container
│   └── [125M]  runAssembly.sif
├── [   1]  misc
│   └── [ 95K]  logo.png
├── [  13]  modules
│   ├── [6.2K]  assembly_graph.py
│   ├── [1.8K]  break_long_reads.py
│   ├── [1.5K]  check_file.py
│   ├── [5.7K]  correct_sequences.py
│   ├── [4.4K]  fastq2fa.py
│   ├── [7.0K]  find_condidate_seeds.py
│   ├── [5.0K]  get_subsample.py
│   ├── [   0]  __init__.py
│   ├── [2.6K]  log.py
│   ├── [2.5K]  newbler_assembly.py
│   ├── [ 32K]  PMAT.py
│   ├── [6.5K]  seeds_extension.py
│   └── [  68]  version.py
└── [4.3K]  README.md

**Comment by bichangwei** [comment]
Please execute and view the printout of the following command **`singularity exec ./PMAT/container/runAssembly.sif runAssembly`**.

**Comment by Mei0110** [comment]
Thank you very much for your reply,
 I found that my previous singularity version=2.4.2-dist, so I upgraded to singularity=3.8.6, and ran the command 

`singularity exec . /PMAT/container/runAssembly.sif runAssembly`

INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting ./PMAT/container/runAssembly.sif: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /w/00/u/user613/miniconda3/envs/PMAT/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /w/00/u/user613/miniconda3/envs/PMAT/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /w/00/u/user613/miniconda3/envs/PMAT/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs: /w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs: no version information available (required by /w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs)
/w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs: symbol lookup error: /w/00/u/user613/miniconda3/envs/PMAT/bin/unsquashfs: undefined symbol: lzo1x_1_compress
: exit status 127

Seems to get the same error reported

**Comment by bichangwei** [comment]
We have fixed some bugs that would cause the above errors, please download and try the latest PMAT!
