### ISSUE TITLE
What is the nextdenovo.cfg file

### ISSUE THREAD

**Issue by SCQUchenyang** [bichangwei/PMAT#10]
Thank you for developing such a useful tool as PMAT. I encountered a problem while using it. I am trying to assemble the mitochondrial genome of Adiantum capillus-veneris. I downloaded one of the PacBio datasets (SRR13170459) from NCBI. Then I converted it to fastq.
![image](https://github.com/bichangwei/PMAT/assets/37470873/f67c7ce2-1900-42ea-8d18-8dfe010f14c1)

I used the following command to assemble it.
```
/data/Zhaijx/cheny/software/PMAT-1.5.2/bin/PMAT autoMito -i SRR13170459.lite.1.fastq -o ./test_clr -st clr -g 4800m -cs nextDenovo -np nextDenovo -cpu 8 -cfg nextdenovo.cfg -m
```
But an error was reported
```
Traceback (most recent call last):
  File "modules/PMAT.py", line 687, in <module>
    args.func(args)
  File "modules/PMAT.py", line 119, in autoMito
    high_quality_seq = correct_sequences.ReadsPreprocess(CANU_PATH, args.cpu, readstype, Output, args.correctcfg).NextDenovo_correct(NEXTDENOVO_PATH)
  File "/data/Zhaijx/cheny/software/PMAT-1.5.2/bin/../modules/correct_sequences.py", line 62, in NextDenovo_correct
    if self.config_info()[1] == 'correct':
  File "/data/Zhaijx/cheny/software/PMAT-1.5.2/bin/../modules/correct_sequences.py", line 137, in config_info
    with open(self.cfg, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'nextdenovo.cfg'
[68776] Failed to execute script 'PMAT' due to unhandled exception!
```
Hope to get your help

**Comment by bichangwei** [comment]
Thank you for using PMAT. You can correct the CLR data using Canu or Nextdenovo before using PMAT, then input the corrected data as HiFi data.

Best,

Changwei
NJFU

---- Replied Message ----
| From | ***@***.***> |
| Date | 02/28/2024 16:54 |
| To | bichangwei/PMAT ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [bichangwei/PMAT] What is the nextdenovo.cfg file (Issue #10) |

Thank you for developing such a useful tool as PMAT. I encountered a problem while using it. I am trying to assemble the mitochondrial genome of Adiantum capillus-veneris. I downloaded one of the PacBio datasets (SRR13170459) from NCBI. Then I converted it to fastq.
image.png (view on web)

I used the following command to assemble it.

/data/Zhaijx/cheny/software/PMAT-1.5.2/bin/PMAT autoMito -i SRR13170459.lite.1.fastq -o ./test_clr -st clr -g 4800m -cs nextDenovo -np nextDenovo -cpu 8 -cfg nextdenovo.cfg -m


But an error was reported

Traceback (most recent call last):
  File "modules/PMAT.py", line 687, in <module>
    args.func(args)
  File "modules/PMAT.py", line 119, in autoMito
    high_quality_seq = correct_sequences.ReadsPreprocess(CANU_PATH, args.cpu, readstype, Output, args.correctcfg).NextDenovo_correct(NEXTDENOVO_PATH)
  File "/data/Zhaijx/cheny/software/PMAT-1.5.2/bin/../modules/correct_sequences.py", line 62, in NextDenovo_correct
    if self.config_info()[1] == 'correct':
  File "/data/Zhaijx/cheny/software/PMAT-1.5.2/bin/../modules/correct_sequences.py", line 137, in config_info
    with open(self.cfg, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'nextdenovo.cfg'
[68776] Failed to execute script 'PMAT' due to unhandled exception!


Hope to get your help
