### ISSUE TITLE
Failed to execute script 'PMAT' due to unhandled exception

### ISSUE THREAD

**Issue by shiyi-pan** [bichangwei/PMAT#7]
Hi, I want to use PAMT to assemble soybean mitochondrial genome, here is my script:

PMAT autoMito -i canu_raw.correctedReads.fasta.gz -o ./19.chloroplast_assembly/07.pmat_data/test1 --task p1 -st ONT -g 1000m -cpu 8

But I met an error, here is my log file:

[ESC[34mESC[1m INFO ESC[0mESC[2m2023-12-03 13:43:27ESC[0m ] The input file is the corrected ONT/CLR or HiFi data
if it is more than one file it needs to be merged into one file
ESC[34mESC[1m
Reads break start...ESC[0m
ESC[2m>>> 2023-12-03 13:48:41ESC[0m
[ESC[34mESC[1m INFO ESC[0mESC[2m2023-12-03 13:50:30ESC[0m ] The raw sequence number is: 1570340
[ESC[34mESC[1m INFO ESC[0mESC[2m2023-12-03 13:50:30ESC[0m ] The processed sequence number is: 2545068
ESC[34mESC[1mReads break end.ESC[0m ESC[2m>>> 2023-12-03 13:50:30ESC[0m
ESC[34mESC[1mReads assembly start...ESC[0m
ESC[2m>>> 2023-12-03 13:50:30ESC[0m
singularity: symbol lookup error: singularity: undefined symbol: seccomp_version
ESC[34mESC[1mReads assembly end.ESC[0m ESC[2m>>> 2023-12-03 13:50:30ESC[0m
Traceback (most recent call last):
  File "modules/PMAT.py", line 687, in <module>
    args.func(args)
  File "modules/PMAT.py", line 136, in autoMito
    assembly_output = runassembly.run_Assembly(args.cpu, assembly_seq_cut_path, Output, args.minidentity, args.minoverlaplen)
  File "/19.chloroplast_assembly/07.pmat_data/PMAT-1.2.2/bin/../modules/runassembly.py", line 64, in run_Assembly
    for rmopt in [os.path.join(runAssembly_output, opt) for opt in os.listdir(runAssembly_output)]:
FileNotFoundError: [Errno 2] No such file or directory: '/19.chloroplast_assembly/07.pmat_data/test1/assembly_result'
[14004] Failed to execute script 'PMAT' due to unhandled exception!

Could you help me fix this error? Thank you very much.

**Comment by xiahouzuoying** [comment]
Hi! I wonder if you've solved the problem yet? I had the same problem.

**Comment by shiyi-pan** [comment]
> Hi! I wonder if you've solved the problem yet? I had the same problem.

I'm sorry to tell you I do not solve it yet.
