### ISSUE TITLE
Error when submit to sge cluster

### ISSUE THREAD

**Issue by Wenfei-Xian** [bichangwei/PMAT#9]
Hey I got the beblow error when it submitted to SGE cluster
```
[ESC[34mESC[1m INFO ESC[0m2024-02-12 20:48:43 ] PMAT v1.5.3
ESC[34mESC[1mUnzip file ...ESC[0m
2024-02-12 20:48:43
[ESC[34mESC[1m INFO ESC[0m2024-02-12 20:48:43 ] Convert format ...
[ESC[34mESC[1m INFO ESC[0m2024-02-12 20:50:57 ] Convert format 134.47s
ESC[34mESC[1mconvert end.ESC[0m
2024-02-12 20:50:58
[ESC[34mESC[1m INFO ESC[0m2024-02-12 20:50:58 ] Formatting in progress ...
[ESC[34mESC[1m INFO ESC[0m2024-02-12 20:51:24 ] Formatting in progress 26.11s
ESC[34mESC[1mReads break start ...ESC[0m
2024-02-12 20:51:29
[ESC[34mESC[1m INFO ESC[0m2024-02-12 20:51:59 ] The raw sequence number is: 634845
[ESC[34mESC[1m INFO ESC[0m2024-02-12 20:51:59 ] The processed sequence number is: 639396
ESC[34mESC[1mReads break end.ESC[0m
2024-02-12 20:51:59
The path of runAssembly : /tmp/global2/wxian/software/PMAT/container/runAssembly.sif
ESC[34mESC[1mReads assembly start ...ESC[0m
2024-02-12 20:51:59
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    gocryptfs not found, will not be able to use gocryptfs
FATAL:   container creation failed: mount hook function failure: mount /proc/self/fd/3->/usr/local/apptainer/1.2.5/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3: squashfuse exited with status 1: fuse: failed to open /dev/fuse: Permission denied
Traceback (most recent call last):
  File "modules/PMAT.py", line 685, in <module>
    args.func(args)
  File "modules/PMAT.py", line 151, in autoMito
    assembly_output = runassembly.run_Assembly(args.cpu, assembly_seq_cut_path, Output, args.minidentity, args.minoverlaplen)
  File "/tmp/global2/wxian/software/PMAT/bin/../modules/runassembly.py", line 66, in run_Assembly
    for rmopt in [os.path.join(runAssembly_output, opt) for opt in os.listdir(runAssembly_output)]:
FileNotFoundError: [Errno 2] No such file or directory: '/ebio/abt6_projects/Dm_3D/data_transfer/zPlastid/zPMAT/Actinidia_chinensis.PMAT/assembly_result'
[1452] Failed to execute script 'PMAT' due to unhandled exception!
```

**Comment by Wenfei-Xian** [comment]
```
[ INFO 2024-02-12 20:59:21 ] PMAT v1.5.3
Unzip file ...
2024-02-12 20:59:21
[ INFO 2024-02-12 20:59:21 ] Convert format ...
[ INFO 2024-02-12 21:01:16 ] Convert format 114.68s
convert end.
2024-02-12 21:01:17
[ INFO 2024-02-12 21:01:17 ] Formatting in progress ...
[ INFO 2024-02-12 21:01:39 ] Formatting in progress 22.01s
Reads break start ...
2024-02-12 21:01:45
[ INFO 2024-02-12 21:02:10 ] The raw sequence number is: 634845
[ INFO 2024-02-12 21:02:10 ] The processed sequence number is: 639396
Reads break end.
2024-02-12 21:02:10
The path of runAssembly : /tmp/global2/wxian/software/PMAT/container/runAssembly.sif
Reads assembly start ...
2024-02-12 21:02:10
Created assembly project directory /data/ebio/abt6_projects/Dm_3D/data_transfer/zPlastid/zPMAT/Actinidia_chinensis.PMAT/assembly_result
1 read file successfully added.
assembly_seq.cut20K.fasta  (Fasta dataset)
Assembly computation starting at: Mon Feb 12 20:02:12 2024  (v3.0 (20140410_1040))
Indexing assembly_seq.cut20K.fasta...
Warning:  No quality scores file found.
-> 100000  -> 200000  -> 300000  -> 400000  -> 500000  -> 600000  -> 639396 reads, 9242531197 bases.   (0.64 million reads, 9.24 GB total)
Checkpointing...
Setting up long overlap detection...
-> 100000 of 639393  -> 200000 of 639393  -> 300000 of 639393  -> 400000 of 639393  -> 500000 of 639393  -> 600000 of 639393  -> 639393 of 639393, 639372 reads to align
Building a tree for 219118320 seeds...
Computing long overlap alignments...
-> 1000 of 639393  -> 4000 of 639393  -> 6000 of 639393  -> 9000 of 639393  -> 11000 of 639393  -> 13000 of 639393  -> 15000 of 639393  -> 17000 of 639393  -> 19000 of 639393  -> 21000 of 639393  -> 23000 of 639393  -> 25000 of 639393  -> 27000 of 639393  -> 29000 of 639393  -> 31000 of 639393  -> 33000 of 639393  -> 35000 of 639393  -> 37000 of 639393  -> 39000 of 639393  -> 41000 of 639393  -> 43000 of 639393  -> 45000 of 639393  -> 47000 of 639393  -> 49000 of 639393  -> 51000 of 639393  -> 53000 of 639393  -> 55000 of 639393  -> 57000 of 639393  -> 59000 of 639393  -> 62000 of 639393  -> 64000 of 639393  -> 66000 of 639393  -> 68000 of 639393  -> 70000 of 639393  -> 72000 of 639393  -> 74000 of 639393  -> 76000 of 639393  -> 78000 of 639393  -> 80000 of 639393  -> 82000 of 639393  -> 84000 of 639393  -> 86000 of 639393  -> 88000 of 639393  -> 90000 of 639393  -> 92000 of 639393  -> 94000 of 639393  -> 96000 of 639393  -> 98000 of 639393  -> 100000 of 639393  -> 102000 of 639393  -> 104000 of 639393  -> 106000 of 639393  -> 108000 of 639393  -> 110000 of 639393  -> 112000 of 639393  -> 114000 of 639393  -> 116000 of 639393  -> 118000 of 639393  -> 120000 of 639393  -> 122000 of 639393  -> 124000 of 639393  -> 126000 of 639393  -> 128000 of 639393  -> 130000 of 639393  -> 132000 of 639393  -> 134000 of 639393  -> 136000 of 639393  -> 138000 of 639393  -> 140000 of 639393  -> 142000 of 639393  -> 144000 of 639393  -> 146000 of 639393  -> 148000 of 639393  -> 150000 of 639393  -> 152000 of 639393  -> 154000 of 639393  -> 156000 of 639393  -> 158000 of 639393  -> 160000 of 639393  -> 162000 of 639393  -> 164000 of 639393  -> 166000 of 639393  -> 168000 of 639393  -> 170000 of 639393  -> 172000 of 639393  -> 174000 of 639393  -> 176000 of 639393  -> 178000 of 639393  -> 180000 of 639393  -> 182000 of 639393  -> 184000 of 639393  -> 186000 of 639393  -> 188000 of 639393  -> 190000 of 639393  -> 192000 of 639393  -> 194000 of 639393  -> 196000 of 639393  -> 198000 of 639393  -> 200000 of 639393  -> 202000 of 639393  -> 204000 of 639393  -> 206000 of 639393  -> 208000 of 639393  -> 210000 of 639393  -> 212000 of 639393  -> 214000 of 639393

Call Stack:
7:  safeAssert(char const*, char const*, unsigned int, char const*)
6:  ChordMatrix::checkAddChordColumn(Chord*, int)
5:  AlignUpdate::updateChords(Sequence*, Sequence*, DiffAlign*, bool, bool, bool, Logger*, DiffAlign*, Timer*)
4:  AlignPhase::asmJobUpdate(AlignAsmJob*, bool)
3:  AlignAsmUpdateThread::run()
2:  Thread::_dispatch(void*)
1:  ()
Thread:  679300416

Error:  An internal error has occurred in the computation.
Assertion:  chord->getLength() > 10
Location: 'bool ChordMatrix::checkAddChordColumn(Chord*, int)'   [ChordMatrix.cpp:229]
Please report this error to your customer support representative.
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    gocryptfs not found, will not be able to use gocryptfs
```
